-- AI company operating layer for Neighborhood Signal.
-- Apply after supabase/schema.sql. Server-side service_role access only.

create table if not exists public.agent_profiles (
  id text primary key,
  organization_id uuid references public.organizations(id) on delete cascade,
  name text not null,
  role text not null,
  mission text not null,
  autonomy text not null check (autonomy in ('observe', 'draft', 'execute-internal')),
  status text not null default 'ready' check (status in ('ready', 'watching', 'blocked')),
  cadence text,
  configuration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  agent_id text references public.agent_profiles(id) on delete set null,
  title text not null,
  priority text not null default 'P2' check (priority in ('P0', 'P1', 'P2')),
  state text not null default 'queued' check (state in ('queued', 'ready', 'running', 'blocked', 'review', 'done', 'cancelled')),
  trigger_text text,
  next_action text,
  payload jsonb not null default '{}'::jsonb,
  requires_human_approval boolean not null default false,
  approved_at timestamptz,
  approved_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_runs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  task_id uuid references public.agent_tasks(id) on delete set null,
  agent_id text references public.agent_profiles(id) on delete set null,
  status text not null check (status in ('started', 'succeeded', 'failed', 'needs_review')),
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists agent_profiles_org_idx on public.agent_profiles (organization_id);
create index if not exists agent_tasks_org_state_priority_idx on public.agent_tasks (organization_id, state, priority, created_at);
create index if not exists agent_tasks_agent_idx on public.agent_tasks (agent_id, created_at desc);
create index if not exists agent_runs_org_started_idx on public.agent_runs (organization_id, started_at desc);
create index if not exists agent_runs_task_idx on public.agent_runs (task_id);

alter table public.agent_profiles enable row level security;
alter table public.agent_tasks enable row level security;
alter table public.agent_runs enable row level security;

revoke all on table public.agent_profiles from anon, authenticated;
revoke all on table public.agent_tasks from anon, authenticated;
revoke all on table public.agent_runs from anon, authenticated;

grant select, insert, update, delete on table public.agent_profiles to service_role;
grant select, insert, update, delete on table public.agent_tasks to service_role;
grant select, insert, update, delete on table public.agent_runs to service_role;
grant usage, select on all sequences in schema public to service_role;
