-- Neighborhood Signal production schema draft.
-- Apply after a Supabase project is selected. Tables are tenant-ready from day one.
create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.territories (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  city text,
  state text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  neighborhood text,
  city text,
  service text,
  completed_at date,
  recommendable boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source text not null,
  external_id text,
  original_text text not null,
  url text,
  neighborhood text,
  city text,
  service text,
  score int not null check (score between 0 and 100),
  urgency text not null,
  recommendation_intent boolean not null default false,
  status text not null default 'new',
  reasons jsonb not null default '[]'::jsonb,
  estimated_value text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, source, external_id)
);

create table if not exists public.keywords (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  phrase text not null,
  kind text not null default 'service',
  weight numeric not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.outreach (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  outreach_type text not null,
  draft text,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  event_type text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.organizations enable row level security;
alter table public.territories enable row level security;
alter table public.customers enable row level security;
alter table public.leads enable row level security;
alter table public.keywords enable row level security;
alter table public.outreach enable row level security;
alter table public.audit_events enable row level security;

-- No broad anon/authenticated policies are intentionally created here.
-- Production auth/organization membership policies should be applied once the auth model is connected.
