import type { Customer, Lead, Territory } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "lead-001",
    source: "Nextdoor",
    externalId: "nd-demo-001",
    author: "Neighbor",
    text: "Can anyone recommend someone in Nocatee to clean, re-sand and seal our driveway pavers? They're faded and the joints are washing out.",
    neighborhood: "Nocatee",
    city: "Ponte Vedra",
    service: "Paver sealing",
    score: 97,
    urgency: "high",
    recommendationIntent: true,
    status: "new",
    publishedAt: "2026-09-11T16:48:00.000Z",
    reasons: ["Direct recommendation request", "Exact service match", "Problem described", "Target territory"],
    estimatedValue: "$1,200–$2,400",
  },
  {
    id: "lead-002",
    source: "Facebook",
    author: "Local homeowner",
    text: "Who do you use for travertine sealing around the pool? Looking to get it done before October.",
    neighborhood: "Twenty Mile",
    city: "Nocatee",
    service: "Travertine sealing",
    score: 92,
    urgency: "medium",
    recommendationIntent: true,
    status: "reviewing",
    publishedAt: "2026-09-11T15:22:00.000Z",
    reasons: ["Vendor recommendation request", "Timing signal", "High-value service"],
    estimatedValue: "$1,400–$3,000",
  },
  {
    id: "lead-003",
    source: "Reddit",
    text: "Any idea what it costs to seal a 3-car paver driveway in Jacksonville? Mine is starting to look chalky.",
    neighborhood: "Southside",
    city: "Jacksonville",
    service: "Paver sealing",
    score: 79,
    urgency: "medium",
    recommendationIntent: false,
    status: "new",
    publishedAt: "2026-09-11T14:05:00.000Z",
    reasons: ["Pricing research", "Problem described", "Local intent"],
    estimatedValue: "$1,300–$2,200",
  },
  {
    id: "lead-004",
    source: "Manual",
    text: "Need someone for pressure washing in Wildlight. House, driveway and back patio.",
    neighborhood: "Wildlight",
    city: "Yulee",
    service: "Pressure washing",
    score: 88,
    urgency: "high",
    recommendationIntent: false,
    status: "contacted",
    publishedAt: "2026-09-11T12:44:00.000Z",
    reasons: ["Explicit need", "Multiple services", "Target territory"],
    estimatedValue: "$350–$850",
  },
  {
    id: "lead-005",
    source: "Nextdoor",
    text: "Our pool deck pavers need fresh sand and sealer. Has anyone had a good experience with a local company near Ponte Vedra Beach?",
    neighborhood: "Sawgrass",
    city: "Ponte Vedra Beach",
    service: "Pool deck sealing",
    score: 95,
    urgency: "high",
    recommendationIntent: true,
    status: "new",
    publishedAt: "2026-09-11T11:57:00.000Z",
    reasons: ["Good-experience recommendation request", "Exact service match", "Premium territory"],
    estimatedValue: "$1,500–$3,500",
  },
];

export const customers: Customer[] = [
  { id: "cust-001", name: "Demo Customer A", neighborhood: "Nocatee", city: "Ponte Vedra", service: "Paver sealing", completedAt: "2026-07-14", recommendable: true },
  { id: "cust-002", name: "Demo Customer B", neighborhood: "Twenty Mile", city: "Nocatee", service: "Travertine sealing", completedAt: "2026-08-19", recommendable: true },
  { id: "cust-003", name: "Demo Customer C", neighborhood: "Nocatee", city: "Ponte Vedra", service: "Paver sealing", completedAt: "2026-06-03", recommendable: true },
  { id: "cust-004", name: "Demo Customer D", neighborhood: "Wildlight", city: "Yulee", service: "Pressure washing", completedAt: "2026-08-25", recommendable: false },
  { id: "cust-005", name: "Demo Customer E", neighborhood: "Sawgrass", city: "Ponte Vedra Beach", service: "Pool deck sealing", completedAt: "2026-05-18", recommendable: true },
];

export const territories: Territory[] = [
  { name: "Nocatee", city: "Ponte Vedra", services: ["Paver sealing", "Travertine sealing", "Pressure washing"], active: true },
  { name: "Ponte Vedra", city: "Ponte Vedra", services: ["Paver sealing", "Pool deck sealing", "Pressure washing"], active: true },
  { name: "St. Johns", city: "St. Johns", services: ["Paver sealing", "Pressure washing"], active: true },
  { name: "Jacksonville", city: "Jacksonville", services: ["Paver sealing", "Pressure washing"], active: true },
  { name: "Yulee", city: "Yulee", services: ["Paver sealing", "Travertine sealing", "Pressure washing"], active: true },
  { name: "Fleming Island", city: "Fleming Island", services: ["Paver sealing", "Pressure washing"], active: true },
];

export const keywords = [
  "paver sealing",
  "seal pavers",
  "paver sealer",
  "travertine sealing",
  "pool deck sealing",
  "re-sand pavers",
  "pressure washing",
  "who do you recommend",
  "looking for someone",
  "need someone to",
];
